[package]
name = "ezekiel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.137", features = ["derive"] }
serde_yaml = "0.8.24"
tera = "1.16.0"
walkdir = "2.3.2"
